### ISSUE TITLE
more example please

### ISSUE THREAD

**Issue by davvit** [KillerCodeMonkey/ngx-quill-angular-cli#2]
Hi, Thank you for this project. Can you please add an example of how to save or get the text from the component?

**Comment by KillerCodeMonkey** [comment]
Just Checkout the readme of ngx-quill? There IS another Demo repo linked
with advanced usages
https://github.com/killerCodeMonkey/ngx-quill-example
https://killercodemonkey.github.io/ngx-quill-example/

use ngModel oder formControl for ordinary angular forms
https://github.com/KillerCodeMonkey/ngx-quill#config

or outputs to get notified about changes:
https://github.com/KillerCodeMonkey/ngx-quill#outputs
